### PR TITLE
Fix NaN bug and all broken tests

### LINKED ISSUE #241: Nan is accepted as valid JSON
The string `NaN` is not valid JSON.  Yet Unmarshaling it does not fail on this input.  In particular, `[1, NaN, 2]` in my experimentation unmarshals to `[]float64{1, 2}`, meaning not only is invalid JSON accepted, but the resulting value doesn't even match what you might expect!

### PR DESCRIPTION
**Pull request by erikdubbelboer**
I have combined all fixes I needed to do to make things testable again in the latest Go version. I thought this was better than making multiple pull requests. If you do want multiple separate ones let me know.

- Fix Makefile to remove all generated files on clean
- Return an error when trying to parse NaN (Fix #241)
- Fix marshalling of RawMessage test (Closes #234)
- Fix float errors in fuzz tests caused by default lib marshaling
  0.00000012 as 1.2e-7 while ffjson doesn't
- Remove invalid TODO

### CODE REVIEW

File: fflib/v1/lexer.go [hunk 1]
```diff
@@ -471,6 +470,7 @@ func (ffl *FFLexer) Scan() FFTok {
 		default:
 			tok = FFTok_error
 			ffl.Error = FFErr_invalid_char
+			goto lexed
```
Comment (erikdubbelboer) [inline fflib/v1/lexer.go]: This one fixes the `NaN` bug (issue #241). Its a complex one line change and I can't fully see the consequences but all tests pass after the change.

**Comment by pquerna** [comment]
Thank you for the PR and the misc fixes!

**Comment by erikdubbelboer** [comment]
Thank you for still maintaining this library.
