### PR TITLE
Put temporary inception file inside the project.

### LINKED ISSUE #163: When ffjson is vendored with GO15VENDOREXPERIMENT, go generate doesn't work.
In one of my projects I have the ffjson package vendored using the GO15VENDOREXPERIMENT method so I can use `ffjson.Encoder`. When I run `go generate`, I get the following error:

```
/var/folders/w0/w_fx2xms6jsf79zwcqq3tbvh0000gn/T/ffjson-inception288838651.go:14: 
cannot use writer.FFJSONExpose() (type 
[]"bitbucket.org/freshmedicalleads/datafuse/vendor/github.com/pquerna/ffjson/shared".InceptionType) 
as type []"github.com/pquerna/ffjson/shared".InceptionType in argument to i.AddMany
```

As you can see, it's trying to use the vendored ffjson package but the executable is expecting the non-vendored version. I assume this is because the inception file is running out of the temp directory instead of the project's source directory; not sure though.

I worked around this for now by just running `GO15VENDOREXPERIMENT=0 go generate`, which I think may stop working once Go 1.7 comes out.  I also tried updating the import path in the temporary file to reference the vendored ffjson instead, and that appeared to work. I don't know if you can detect the presence of a vendored package when automatically building the source though.

The source file I'm using with ffjson as well as my edited temp file that builds successfully is here: https://gist.github.com/dimfeld/10e2d19144a8f9cced83

FWIW this wasn't a problem when I used `gb`. I suppose its GOPATH trickery avoids this problem.

### PR DESCRIPTION
**Pull request by dimfeld**
A temporary directory is generated to avoid package name problems.

Fixes #163

### CODE REVIEW

**Comment by dimfeld** [comment]
I tried running tests but ff_invalid_test failed to compile both with and without my changes. It works on the project I referenced in the original issue though.

File: generator/inceptionmain.go [hunk 1]
```diff
@@ -234,6 +241,7 @@ func (im *InceptionMain) Run() error {
 
 		os.Remove(im.TempMainPath)
 		os.Remove(im.exposePath)
+		os.Remove(im.tempDir)
```
Comment (pquerna) [inline generator/inceptionmain.go]: Wondering if this should be `os.RemoveAll`?

Comment (dimfeld) [inline generator/inceptionmain.go]: Sure, we can do that. I don't think there should be anything else in the directory except the file removed on line 242, but it can't hurt.

Comment (pquerna) [inline generator/inceptionmain.go]: Probably fine as is with a little more thought, we aren't creating any other files in the dir, so a single `Remove` should work fine.

**Comment by dimfeld** [comment]
Are you waiting for anything else from me on this one?

**Comment by dimfeld** [comment]
Thanks Paul!
